config/routes.rb
Rails.application.routes.draw do

  resources :products do
    resources :reviews, only: [:show, :create, :destroy]
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: true
	validates :description, presence: true
	validates :price_in_cents, numericality: {only_integer: true}

	def formatted_price
		price_in_dollars = price_in_cents.to_f / 100
		sprintf("%.2f", price_in_dollars)
	end

	has_many :reviews
	has_many :users, through: :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :name, presence: true
	validates :email, presence: true 

	has_many :reviews
	has_many :products, through: :users


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in!"
  		redirect_to new_session_path
  	end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def find_product
    @product = Product.find(params[:id])
  end

  def index
    @products = Product.order('products.created_at DESC').page(params[:page])
    if params[:search]
      @products = @products.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    end

    # if request.xhr?
    #   render @products
    # end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end
  end

  def edit
    @product = product
  end
  
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = find_product
    @product.destroy
    redirect_to product_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product
  before_filter :ensure_logged_in, only:  [:create, :destroy]

  def show
  	@review = Review.find(params[:id])
  end

  def create
  	@review = @product.reviews.build(review_params)
  	@review.user = current_user

  	 # Check out this article on [.build](http://stackoverflow.com/questions/783584/ruby-on-rails-how-do-i-use-the-active-record-build-method-in-a-belongs-to-rel)
    # You could use a longer alternate syntax if it makes more sense to you
    # 
    # @review = Review.new(
    #   comment: params[:review][:comment],
    #   product_id: @product.id,
    #   user_id: current_user.id
    # )

    respond_to do |format|
    	if @review.save
    		format.html {redirect_to product_path(@product.id), notice: 'Review posted!' }
        format.js {} 
    	else
    		render 'products/show', alert: 'There was an error. Review couldn\'t be created.'
        format.js{}
    	end
    end
  end

  def destroy
  	@review = Review.find(params[:id])
  	@review.destroy
  end

  private
  def review_params
  	params.require(:review).permit(:title, :comment, :product_id)
  end

  def load_product
  	@product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to products_url, notice: "Logged in!"
  	else
  		flash.now[:alert] = "Invalid email or password."
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to products_url, notice: "Signed up!"
  	else
  		render :new
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Rainforest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if flash[:notice] %>
		<p id="notice"><%= flash[:notice] %></p>
	<% end %>

	<% if flash[:alert] %>
		<p id="alert"><%= flash[:alert] %></p>
	<% end %>
	<header>
	<h1>Rainforest</h1>

	<p class="userinfo">
		<% if current_user %>
			Signed in as <%= current_user.name %>.<br>
			<%= link_to "Log Out", session_path("current"), :method => :delete %>
		<% else %>
			<%= link_to "Log In", new_session_path %> or 
			<%= link_to "Sign Up", new_user_path %>
		<% end %>
	</p>
	</header>
	
<%= yield %>



</body>
</html>

app/views/products/_form.html.erb
<%= form_for (@product) do |f|  %>
	
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :description %>
		<%= f.text_field :description %>
	</div>

	<div class="field">
		<%=  f.label :price_in_cents %>
		<%= f.number_field :price_in_cents %>
	</div>
	
	<div class="actions">
		<%= f.submit %>
	</div>
	
	<% if @product.errors.any? %>

		<div id="error_explanation">
			<h3><%= pluralize(@product.errors.count, "error") %> occurred when trying to create a new product:</h3>

			<% @product.errors.full_messages.each do |error| %>
				<li><%= error %></li>
			<% end %>
		</div>
	<% end %>

<% end %>

app/views/products/_product.html.erb
<p><strong><%= link_to product.name, product %></strong></p>
	<p><strong>Description: </strong><%= product.description %></p>
	<p><strong>Price: </strong>$<%= product.formatted_price %></p>
	<br>

app/views/products/_reviews.html.erb
	<% @product.reviews.each do |review| %>
	<h4><%= review.title %></h4>
	<p> <%= review.comment %>
		<% if review.user != nil %>
			<p><em>By: <%= review.user.email %></em></p>
			<p>Added on: <%= review.created_at %></p>
		<% end %>
	<% end %>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<%=  link_to "Add a product", new_product_path, class: "add-product"%>

	<h3>Products <small><%= page_entries_info @products %></small></h3>
<!-- <a href="" id="my-link" data-message="Someone clicked me!">My Link</a> -->

<!-- <script>
	$("#my-link").click(function(){
		alert($(this).data("message"));
	});
</script> -->

<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search" %>
	<% end %>

<h3>All Products</h3>

<div id="products">
	<%= render @products %>
</div>

<%= paginate @products %>

<!-- <script type="text/javascript">
	function display_search_results() {
		if (this.readyState === 4) {
			console.log(this)
			document.getElementById('products').innerHTML = this.responseText;
		}
	}
	var form = document.getElementById('search-form');
	form.addEventListener('submit', function(event){ 
		event.preventDefault();
		var searchValue = document.getElementById('search').value;
	
		var xhr = new XMLHttpRequest();
		xhr.onload = display_search_results;
		xhr.open('GET', '/products?search=' + searchValue, true)
		xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
		xhr.send()
	});
 </script> -->

app/views/products/index.js.erb
<% if params[:search] %>
	$('#products').html("<%= escape_javascript(render @products) %>");
<% else %>
 	$('#products').append('<%= j render(@products) %>');
<% end %>

$('.pagination').replaceWith('<%= j paginate(@products) %>')

app/views/products/new.html.erb
w<h1>Enter in a New Product</h1>

<%= render 'form' %>

<br>

<%= link_to 'Back To Products', products_path %>

app/views/products/show.html.erb
<h4><%= link_to "Back To Products", products_path %></h4>

<h1><%= @product.name %></h1>

<h3>$<%= @product.formatted_price %></h3>

<p><%= @product.description %></p>

<h2 style="text-decoration: underline;">Reviews</h2>

<div id="review-list">
	<%= render :partial => "reviews" %>
</div>

<div id="new-review">
	<% if current_user %>
		<h3>Add a new review</h3>

		<%= form_for([@product, @review], :remote => true) do |f| %>

			<% if @review.errors.any? %>
				<div id="error_explanation">
					<h3> <%= pluralize(@reviews.errors.count, "error") %> occured when trying to submit your review</h3>

					<ul>
						<% @reviews.errors.full_messages.each do |error| %>
							<li><%= error %></li>
						<% end %>
					</ul>
				</div>
			<% end %>
			
			<div class="field">
				<%= f.label :title %><br>
				<%= f.text_field :title %>
			</div>

			<div class="field">
				<%= f.label :comment %><br>
				<%= f.text_field :comment %>
			</div>

			<div class="actions" style="margin-top: 10px;">
				<%= f.submit %>
			</div>

		<% end %>

	<% else %>
		<p>Please <%= link_to "log in", new_session_path %> to write a new review.</p>

	<% end %>
</div>

<script type="text/javascript">
	$(function(){
		$("#new_review")
			.on('ajax:beforeSend', function() {
				$("input[type='submit']")
				.val('Saving review...')
				.attr('disabled', 'disabled');
			})

			.on('ajax:complete', function() {
				$("input[type='submit']")
				.val('Create Review')
				.removeAttr('disabled');
			});
	});
</script>

app/views/products/show.js.erb
$('body').append("<%= escape_javascript(render @product) %>")

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/create.js.erb
$("#review-list").html("<%= escape_javascript(render(:partial => 'products/reviews')) %>")

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign-up</h1>

<%= form_for @user do |f|%>

	<% if @user.errors.any? %>
		<h2>Oops we couldn't sign you up just yet!</h2>
		<ul>
			 <% for message in @user.errors.full_messages %>
			 <li><%= message %></li>
			 <% end %>
	<% end %>

	<div class="field">
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</div>
	
	<div class="field">
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %>
	</div>

	<div class="action">
		<%= f.submit %>
	</div>
	
	
<% end %>